name: Local Self-Hosted Deploy
on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: self-hosted
    steps:
      - name: Run the deploy script
        # The '-l' flag stands for "login shell"
        run: bash -l ~/projs_etc/kareem_sir_research_app/deploy.sh
